import { ContentProviderConfig, ContentProviderAuthData, ContentItem, ContentFile, ProviderLogos, ProviderCapabilities, IProvider, AuthType, Instructions, InstructionItem, CurrentPlan } from "../../interfaces";
import { parsePath } from "../../pathUtils";
import lifeChurchData from "./data.json";
import { LifeChurchData, LifeChurchSeries, LifeChurchUnit, LifeChurchLesson, LifeChurchScheduledLesson } from "./LifeChurchInterfaces";

/**
 * Life.Church Provider
 *
 * Browses the Life.Church kids curriculum from a static catalog generated by
 * scripts/scrape-lifechurch.ts (sourced from life.church/media/* + the
 * open.life.church weekly calendar).
 *
 * Path structure:
 *   /                                       -> "scheduled" folder + 4 series
 *   /scheduled                              -> this Sunday's scheduled lessons (one per age group)
 *   /scheduled/{scheduledId}                -> single video file (leaf)
 *   /{seriesId}                             -> units within the series
 *   /{seriesId}/{unitId}                    -> lessons within the unit
 *   /{seriesId}/{unitId}/{lessonId}         -> single video file (leaf)
 *
 * Video delivery: ContentFile.url is a direct mp4 on Life.Church's CDN
 * (https://d.life.church/.../{slug}_720p.mp4). Public, no auth, supports
 * range requests — plays in any standard mp4 player including
 * react-native-video.
 */
export class LifeChurchProvider implements IProvider {
  readonly id = "lifechurch";
  readonly name = "Life.Church";

  readonly logos: ProviderLogos = {
    light: "https://cdn.brandfetch.io/idRrA6pM45/w/400/h/400/theme/dark/icon.jpeg?c=1bxid64Mup7aczewSAYMX&t=1668042253613",
    dark: "https://cdn.brandfetch.io/idRrA6pM45/w/400/h/400/theme/dark/icon.jpeg?c=1bxid64Mup7aczewSAYMX&t=1668042253613"
  };

  readonly config: ContentProviderConfig = {
    id: "lifechurch",
    name: "Life.Church",
    apiBase: "https://www.life.church",
    oauthBase: "",
    clientId: "",
    scopes: [],
    endpoints: {}
  };

  readonly requiresAuth = false;
  readonly authTypes: AuthType[] = ["none"];
  readonly capabilities: ProviderCapabilities = {
    browse: true,
    presentations: true,
    playlist: true,
    instructions: true,
    mediaLicensing: false
  };

  private data: LifeChurchData = lifeChurchData as LifeChurchData;

  private findSeries(seriesId: string): LifeChurchSeries | undefined {
    return this.data.series.find(s => s.id === seriesId);
  }

  private findUnit(series: LifeChurchSeries, unitId: string): LifeChurchUnit | undefined {
    return series.units.find(u => u.id === unitId);
  }

  private findLesson(unit: LifeChurchUnit, lessonId: string): LifeChurchLesson | undefined {
    return unit.lessons.find(l => l.id === lessonId);
  }

  private findScheduled(scheduledId: string): LifeChurchScheduledLesson | undefined {
    return this.data.scheduledLessons?.find(s => s.id === scheduledId);
  }

  /** Resolve a scheduled-lesson reference to the underlying lesson + unit + series. */
  private resolveScheduled(sched: LifeChurchScheduledLesson): { series: LifeChurchSeries; unit: LifeChurchUnit; lesson: LifeChurchLesson } | null {
    const series = this.findSeries(sched.seriesId);
    const unit = series && this.findUnit(series, sched.unitId);
    const lesson = unit && this.findLesson(unit, sched.lessonId);
    if (!series || !unit || !lesson) return null;
    return { series, unit, lesson };
  }

  private lessonToFile(lesson: LifeChurchLesson, overrideTitle?: string): ContentFile {
    return {
      type: "file",
      id: lesson.id,
      title: overrideTitle ?? lesson.title,
      mediaType: "video",
      url: lesson.videoUrl,
      thumbnail: lesson.thumbnail,
      providerData: { sourceUrl: lesson.sourceUrl }
    };
  }

  async browse(path?: string | null, _auth?: ContentProviderAuthData | null): Promise<ContentItem[]> {
    const { segments, depth } = parsePath(path);

    if (depth === 0) {
      const items: ContentItem[] = [];
      if (this.data.scheduledLessons && this.data.scheduledLessons.length > 0) {
        items.push({
          type: "folder",
          id: "scheduled",
          title: "This Sunday",
          path: "/scheduled"
        });
      }
      for (const s of this.data.series) {
        items.push({ type: "folder", id: s.id, title: s.name, thumbnail: s.thumbnail, path: `/${s.id}` });
      }
      return items;
    }

    if (segments[0] === "scheduled") {
      if (depth === 1) {
        return (this.data.scheduledLessons ?? []).map(s => {
          const resolved = this.resolveScheduled(s);
          return {
            type: "folder" as const,
            id: s.id,
            title: `${s.ageGroup} — ${resolved?.lesson.title ?? s.sourceTitle}`,
            thumbnail: resolved?.lesson.thumbnail ?? resolved?.unit.thumbnail,
            isLeaf: true,
            path: `/scheduled/${s.id}`
          };
        });
      }
      if (depth === 2) {
        const sched = this.findScheduled(segments[1]);
        const resolved = sched && this.resolveScheduled(sched);
        if (!sched || !resolved) return [];
        return [this.lessonToFile(resolved.lesson, `${sched.ageGroup} — ${resolved.lesson.title}`)];
      }
      return [];
    }

    if (depth === 1) {
      const series = this.findSeries(segments[0]);
      if (!series) return [];
      return series.units.map(u => ({
        type: "folder" as const,
        id: u.id,
        title: u.name,
        thumbnail: u.thumbnail ?? series.thumbnail,
        path: `/${series.id}/${u.id}`
      }));
    }

    if (depth === 2) {
      const series = this.findSeries(segments[0]);
      const unit = series && this.findUnit(series, segments[1]);
      if (!series || !unit) return [];
      return unit.lessons.map(l => ({
        type: "folder" as const,
        id: l.id,
        title: l.title,
        thumbnail: l.thumbnail,
        isLeaf: true,
        path: `/${series.id}/${unit.id}/${l.id}`
      }));
    }

    if (depth === 3) {
      const series = this.findSeries(segments[0]);
      const unit = series && this.findUnit(series, segments[1]);
      const lesson = unit && this.findLesson(unit, segments[2]);
      if (!lesson) return [];
      return [this.lessonToFile(lesson)];
    }

    return [];
  }

  async getPlaylist(path: string, _auth?: ContentProviderAuthData | null, _resolution?: number): Promise<ContentFile[] | null> {
    const { segments, depth } = parsePath(path);

    if (segments[0] === "scheduled" && depth === 2) {
      const sched = this.findScheduled(segments[1]);
      const resolved = sched && this.resolveScheduled(sched);
      return resolved ? [this.lessonToFile(resolved.lesson, `${sched!.ageGroup} — ${resolved.lesson.title}`)] : null;
    }

    if (depth === 3) {
      const series = this.findSeries(segments[0]);
      const unit = series && this.findUnit(series, segments[1]);
      const lesson = unit && this.findLesson(unit, segments[2]);
      return lesson ? [this.lessonToFile(lesson)] : null;
    }

    if (depth === 2 && segments[0] !== "scheduled") {
      const series = this.findSeries(segments[0]);
      const unit = series && this.findUnit(series, segments[1]);
      if (!unit) return null;
      const files = unit.lessons.map(l => this.lessonToFile(l));
      return files.length > 0 ? files : null;
    }

    return null;
  }

  async getInstructions(path: string, _auth?: ContentProviderAuthData | null): Promise<Instructions | null> {
    const { segments, depth } = parsePath(path);

    const buildItem = (lesson: LifeChurchLesson, label?: string): InstructionItem => ({
      id: `${lesson.id}-action`,
      itemType: "action",
      label: label ?? lesson.title,
      actionType: "play",
      children: [
        {
          id: lesson.id,
          itemType: "file",
          label: label ?? lesson.title,
          downloadUrl: lesson.videoUrl,
          thumbnail: lesson.thumbnail,
          mediaType: "video"
        }
      ]
    });

    if (segments[0] === "scheduled" && depth === 2) {
      const sched = this.findScheduled(segments[1]);
      const resolved = sched && this.resolveScheduled(sched);
      if (!sched || !resolved) return null;
      const label = `${sched.ageGroup} — ${resolved.lesson.title}`;
      return {
        name: label,
        items: [{ id: `scheduled-${sched.id}-section`, itemType: "section", label: "This Sunday", children: [buildItem(resolved.lesson, label)] }]
      };
    }

    if (depth === 3) {
      const series = this.findSeries(segments[0]);
      const unit = series && this.findUnit(series, segments[1]);
      const lesson = unit && this.findLesson(unit, segments[2]);
      if (!series || !unit || !lesson) return null;
      return { name: lesson.title, items: [{ id: `${unit.id}-section`, itemType: "section", label: unit.name, children: [buildItem(lesson)] }] };
    }

    if (depth === 2 && segments[0] !== "scheduled") {
      const series = this.findSeries(segments[0]);
      const unit = series && this.findUnit(series, segments[1]);
      if (!unit) return null;
      return { name: unit.name, items: [{ id: `${unit.id}-section`, itemType: "section", label: unit.name, children: unit.lessons.map(l => buildItem(l)) }] };
    }

    return null;
  }

  /**
   * Returns the most recent scheduled lesson from data.scheduledLessons.
   */
  async getCurrentPlan(_auth?: ContentProviderAuthData | null): Promise<CurrentPlan | null> {
    const all = this.data.scheduledLessons ?? [];
    if (all.length === 0) return null;

    const sched = [...all].sort((a, b) => b.weekOf.localeCompare(a.weekOf))[0];
    const resolved = this.resolveScheduled(sched);
    if (!resolved) return null;

    const { lesson } = resolved;
    return {
      id: sched.id,
      title: `${sched.ageGroup} — ${lesson.title}`,
      serviceDate: sched.weekOf,
      thumbnail: lesson.thumbnail ?? resolved.unit.thumbnail ?? resolved.series.thumbnail,
      files: [
        {
          id: lesson.id,
          name: lesson.title,
          url: lesson.videoUrl,
          image: lesson.thumbnail,
          seconds: 0
        }
      ]
    };
  }

  supportsDeviceFlow(): boolean {
    return false;
  }
}
